/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from '@react-three/drei'
import React, { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Cylinder013: THREE.Mesh
    Cylinder013_1: THREE.Mesh
    Book1_1: THREE.Mesh
    Book1_2: THREE.Mesh
    Shelf1: THREE.Mesh
    Shelf2: THREE.Mesh
    Cube028: THREE.Mesh
    Cube028_1: THREE.Mesh
    Door_1: THREE.Mesh
    Door_2: THREE.Mesh
    Shelf3: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
    Cylinder015_3: THREE.Mesh
    Bench: THREE.Mesh
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube035: THREE.Mesh
    Cube035_1: THREE.Mesh
    Cube036: THREE.Mesh
    Cube036_1: THREE.Mesh
    Cube037: THREE.Mesh
    Cube037_1: THREE.Mesh
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Table: THREE.Mesh
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
    Cube021: THREE.Mesh
    Cube021_1: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder010_1: THREE.Mesh
    Cylinder010_2: THREE.Mesh
    ChairDoc: THREE.Mesh
    Wall1: THREE.Mesh
    Wall2: THREE.Mesh
    Wall3: THREE.Mesh
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
    CompLeg: THREE.Mesh
  }
  materials: {
    MaterialFloor: THREE.MeshStandardMaterial
    MaterialRed: THREE.MeshStandardMaterial
    MaterialWhite: THREE.MeshStandardMaterial
    MaterialBlue: THREE.MeshStandardMaterial
    MaterialDoorWood: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    MaterialMetalDoorHand: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    MaterialLockerHand: THREE.MeshStandardMaterial
    MaterialBenchWood: THREE.MeshStandardMaterial
    MaterialGreen: THREE.MeshStandardMaterial
    MaterialMetalBin: THREE.MeshStandardMaterial
    MaterialTable: THREE.MeshStandardMaterial
    MaterialChairWood: THREE.MeshStandardMaterial
    MaterialCuireBlack: THREE.MeshStandardMaterial
    MaterialSteelGray: THREE.MeshStandardMaterial
    MaterialMedChairLegBlack: THREE.MeshStandardMaterial
    MaterialMedChairLeg: THREE.MeshStandardMaterial
    MaterialWall: THREE.MeshStandardMaterial
    MaterialCompLeg: THREE.MeshStandardMaterial
    MaterialCompScreen: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/virtual_room_2.glb') as GLTFResult
  const tableWoodTexture = useTexture('/textures/wood3.jpg')
  const leatherTexture = useTexture('/textures/leather.png')
  const treeBenchTexture = useTexture('/textures/tree.png')
  const floorTexture = useTexture('/textures/wood_fl.png')
  const lockerWoodTexture = useTexture('/textures/wood1.jpg')
  const metalTexture = useTexture('/textures/metal2.jpg')
  const wallTexture = useTexture('/textures/wall1.png')

  return (
    <group ref={group as any} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        position={[1.57, -5.52, -9.63]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={25}
      >
        <meshBasicMaterial map={floorTexture} map-flipY={false} />
      </mesh>
      <group
        position={[-7.9, -0.49, 1.66]}
        rotation={[Math.PI / 2, -1.57, 0]}
        scale={[0.21, 0.83, 0.23]}
      >
        <mesh
          geometry={nodes.Cylinder013.geometry}
          material={materials.MaterialRed}
        />
        <mesh
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.MaterialWhite}
        />
      </group>
      <group
        position={[-8.01, -0.05, 1.49]}
        rotation={[Math.PI / 2, -1.57, 0]}
        scale={[0.21, 0.83, 0.23]}
      >
        <mesh
          geometry={nodes.Book1_1.geometry}
          material={materials.MaterialBlue}
        />
        <mesh
          geometry={nodes.Book1_2.geometry}
          material={materials.MaterialWhite}
        />
      </group>
      <mesh
        geometry={nodes.Shelf1.geometry}
        position={[24.42, -5.59, -21.19]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[5, 3.5, 4]}
      >
        <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
      </mesh>
      <mesh
        geometry={nodes.Shelf2.geometry}
        position={[24.47, -5.76, -13.21]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[3, 5, 4]}
      >
        <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
      </mesh>
      <group
        position={[2.25, 7.87, -34.36]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.23, 3.04, 2.92]}
      >
        <mesh
          geometry={nodes.Cube028.geometry}
          material={materials['Material.036']}
        />
        <mesh
          geometry={nodes.Cube028_1.geometry}
          material={materials['Material.037']}
        />
      </group>
      <group
        position={[18.39, 2.92, -33.9]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.15, 8, 5]}
      >
        <mesh geometry={nodes.Door_1.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Door_2.geometry}
          material={materials.MaterialMetalDoorHand}
        />
      </group>
      <mesh
        geometry={nodes.Shelf3.geometry}
        position={[-11.74, -5.76, -32.48]}
        scale={[3, 5, 4]}
      >
        <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
      </mesh>
      <group
        position={[-6.45, -0.59, 1.28]}
        rotation={[Math.PI / 2, -1.57, 0]}
        scale={[0.07, 0.69, 0.07]}
      >
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={materials['Material.041']}
        />
        <mesh
          geometry={nodes.Cylinder015_1.geometry}
          material={materials['Material.042']}
        />
        <mesh
          geometry={nodes.Cylinder015_2.geometry}
          material={materials['Material.043']}
        />
        <mesh
          geometry={nodes.Cylinder015_3.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <mesh
        geometry={nodes.Bench.geometry}
        position={[-20.82, -2.31, -15.02]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[10.9, 0.19, 1.92]}
      >
        <meshBasicMaterial map={treeBenchTexture} map-flipY={false} />
      </mesh>
      <group
        position={[6.28, -3.08, -30.36]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.08, 1.95, 2.72]}
      >
        <mesh geometry={nodes.Cube034.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Cube034_1.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <group
        position={[0.28, -3.08, -30.36]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.08, 1.95, 2.85]}
      >
        <mesh geometry={nodes.Cube035.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Cube035_1.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <group
        position={[-11.7, -3.08, -30.36]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={[0.08, 1.95, 2.83]}
      >
        <mesh geometry={nodes.Cube036.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Cube036_1.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <group
        position={[22.36, -2.92, -13.29]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.08, 1.95, 2.72]}
      >
        <mesh geometry={nodes.Cube037.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Cube037_1.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <group
        position={[22.36, -2.92, -7.2]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.08, 1.95, 2.72]}
      >
        <mesh geometry={nodes.Cube038.geometry}>
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          geometry={nodes.Cube038_1.geometry}
          material={materials.MaterialLockerHand}
        />
      </group>
      <group
        position={[23.94, -4.03, -30.2]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.4}
      >
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={materials.MaterialGreen}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={materials.MaterialMetalBin}
        />
      </group>
      <mesh
        geometry={nodes.Table.geometry}
        position={[-8.33, -3.17, 2.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.18, 2.19, 0.12]}
      >
        <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
      </mesh>
      <group
        position={[0.36, 1.32, -9.12]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.1, 0.41, 0.15]}
      >
        <mesh geometry={nodes.Cube014.geometry}>
          <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
        </mesh>
        <mesh geometry={nodes.Cube014_1.geometry}>
          <meshBasicMaterial map={leatherTexture} map-flipY={false} />
        </mesh>
      </group>
      <group
        position={[-6.24, 1.32, -9.12]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.1, 0.41, 0.15]}
      >
        <mesh geometry={nodes.Cube021.geometry}>
          <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
        </mesh>
        <mesh geometry={nodes.Cube021_1.geometry}>
          <meshBasicMaterial map={leatherTexture} map-flipY={false} />
        </mesh>
      </group>
      <group
        position={[-4.53, -3.55, 8.38]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.23, 1.52, 0.23]}
      >
        <mesh geometry={nodes.Cylinder010.geometry}>
          <meshBasicMaterial map={metalTexture} map-flipY={false} />
        </mesh>
        <mesh geometry={nodes.Cylinder010_1.geometry}>
          <meshBasicMaterial map={leatherTexture} map-flipY={false} />
        </mesh>
        <mesh geometry={nodes.Cylinder010_2.geometry}>
          <meshBasicMaterial map={metalTexture} map-flipY={false} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.ChairDoc.geometry}
        position={[-4.75, -1.83, 7.9]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.36, 0.27, 2.28]}
      >
        <meshBasicMaterial map={leatherTexture} map-flipY={false} />
      </mesh>
      <mesh
        geometry={nodes.Wall1.geometry}
        position={[26.53, 4.56, -9.43]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[10, 25, 25]}
      >
        <meshBasicMaterial map={wallTexture} map-flipY={false} />
      </mesh>
      <mesh
        geometry={nodes.Wall2.geometry}
        position={[-23.4, 4.56, -9.43]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[10, 25, 25]}
      >
        <meshBasicMaterial map={wallTexture} map-flipY={false} />
      </mesh>
      <mesh
        geometry={nodes.Wall3.geometry}
        position={[1.62, 4.56, -34.59]}
        rotation={[Math.PI / 2, -1.57, 0]}
        scale={[10, 25, 25]}
      >
        <meshBasicMaterial map={wallTexture} map-flipY={false} />
      </mesh>
      <group
        position={[2.3, 1.22, 1.08]}
        rotation={[1.4, -0.07, 0.35]}
        scale={0.23}
      >
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials.MaterialCompLeg}
        />
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials.MaterialCompScreen}
        />
      </group>
      <mesh
        geometry={nodes.CompLeg.geometry}
        material={materials.MaterialCompLeg}
        position={[2.27, -0.59, 1.13]}
        rotation={[0, -0.36, 0]}
        scale={[0.21, 0.21, 0.13]}
      />
    </group>
  )
}

useGLTF.preload('/virtual_room_2.glb')
