/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF, useTexture } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ch07_Body: THREE.SkinnedMesh
    Ch07_Eyelashes: THREE.SkinnedMesh
    Ch07_Hair: THREE.SkinnedMesh
    Ch07_Heels: THREE.SkinnedMesh
    Ch07_Pants: THREE.SkinnedMesh
    Ch07_Shirt: THREE.SkinnedMesh
    Ch07_Suit: THREE.SkinnedMesh
    Ch16_Body1: THREE.SkinnedMesh
    Ch16_Cap: THREE.SkinnedMesh
    Ch16_Eyelashes: THREE.SkinnedMesh
    Ch16_Mask: THREE.SkinnedMesh
    Ch16_Pants: THREE.SkinnedMesh
    Ch16_Shirt: THREE.SkinnedMesh
    Ch16_Shoes: THREE.SkinnedMesh
    Plane: THREE.Mesh
    Cylinder013: THREE.Mesh
    Cylinder013_1: THREE.Mesh
    Book1_1: THREE.Mesh
    Book1_2: THREE.Mesh
    Shelf1: THREE.Mesh
    Shelf2: THREE.Mesh
    Cube028: THREE.Mesh
    Cube028_1: THREE.Mesh
    Door_1: THREE.Mesh
    Door_2: THREE.Mesh
    Shelf3: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
    Cylinder015_3: THREE.Mesh
    Bench: THREE.Mesh
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube035: THREE.Mesh
    Cube035_1: THREE.Mesh
    Cube036: THREE.Mesh
    Cube036_1: THREE.Mesh
    Cube037: THREE.Mesh
    Cube037_1: THREE.Mesh
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Table: THREE.Mesh
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
    Cube021: THREE.Mesh
    Cube021_1: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder010_1: THREE.Mesh
    Cylinder010_2: THREE.Mesh
    Cube025: THREE.Mesh
    Cube025_1: THREE.Mesh
    Wall1: THREE.Mesh
    Wall2: THREE.Mesh
    Wall4: THREE.Mesh
    Wall4001: THREE.Mesh
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
    CompLeg: THREE.Mesh
    mixamorig8Hips: THREE.Bone
    mixamorigHips: THREE.Bone
  }
  materials: {
    Ch07_body: THREE.MeshStandardMaterial
    Ch07_hair: THREE.MeshStandardMaterial
    ['Ch16_Body.002']: THREE.MeshStandardMaterial
    ['Ch16_body1.002']: THREE.MeshStandardMaterial
    ['Ch16_eyelashes.002']: THREE.MeshStandardMaterial
    MaterialFloor: THREE.MeshStandardMaterial
    MaterialRed: THREE.MeshStandardMaterial
    MaterialWhite: THREE.MeshStandardMaterial
    MaterialBlue: THREE.MeshStandardMaterial
    MaterialDoorWood: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    MaterialMetalDoorHand: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    MaterialLockerHand: THREE.MeshStandardMaterial
    MaterialBenchWood: THREE.MeshStandardMaterial
    MaterialGreen: THREE.MeshStandardMaterial
    MaterialMetalBin: THREE.MeshStandardMaterial
    MaterialTable: THREE.MeshStandardMaterial
    MaterialChairWood: THREE.MeshStandardMaterial
    MaterialCuireBlack: THREE.MeshStandardMaterial
    MaterialSteelGray: THREE.MeshStandardMaterial
    MaterialMedChairLegBlack: THREE.MeshStandardMaterial
    MaterialMedChairLeg: THREE.MeshStandardMaterial
    MaterialWall: THREE.MeshStandardMaterial
    MaterialCompLeg: THREE.MeshStandardMaterial
    MaterialCompScreen: THREE.MeshStandardMaterial
  }
}

type ActionName =
  | 'Chair1Action'
  | 'CubeAction.002'
  | 'CubeAction'
  | 'CubeAction.004'
  | 'CubeAction.006'
  | 'talk_pat'
  | 'talk_doc'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(
    '/virtual_room_users_2.glb',
  ) as GLTFResult
  const tableWoodTexture = useTexture('/textures/wood3.jpg')
  const leatherTexture = useTexture('/textures/leather.png')
  const treeBenchTexture = useTexture('/textures/tree.png')
  const floorTexture = useTexture('/textures/wood_fl.png')
  const lockerWoodTexture = useTexture('/textures/wood1.jpg')
  const metalTexture = useTexture('/textures/metal2.jpg')
  const wallTexture = useTexture('/textures/wall1.png')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.talk_pat?.play()
    actions.talk_doc?.play()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <group ref={group as any} {...props} dispose={null}>
      <group name='Scene'>
        <group
          name='Point'
          position={[-5.58, -0.42, 11.13]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <group
          name='Light'
          position={[-6.41, 4.83, 1.17]}
          rotation={[1.25, -0.88, 1.1]}
        />
        <group
          name='Empty'
          position={[2.25, 7.87, -34.23]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.15}
        />
        <group
          name='patient'
          position={[0.36, -5.64, -8.37]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.06, 0.07, 0.06]}
        >
          <primitive object={nodes.mixamorig8Hips} />
          <skinnedMesh
            name='Ch07_Body'
            geometry={nodes.Ch07_Body.geometry}
            material={materials.Ch07_body}
            skeleton={nodes.Ch07_Body.skeleton}
          />
          <skinnedMesh
            name='Ch07_Eyelashes'
            geometry={nodes.Ch07_Eyelashes.geometry}
            material={materials.Ch07_hair}
            skeleton={nodes.Ch07_Eyelashes.skeleton}
          />
          <skinnedMesh
            name='Ch07_Hair'
            geometry={nodes.Ch07_Hair.geometry}
            material={materials.Ch07_hair}
            skeleton={nodes.Ch07_Hair.skeleton}
          />
          <skinnedMesh
            name='Ch07_Heels'
            geometry={nodes.Ch07_Heels.geometry}
            material={materials.Ch07_body}
            skeleton={nodes.Ch07_Heels.skeleton}
          />
          <skinnedMesh
            name='Ch07_Pants'
            geometry={nodes.Ch07_Pants.geometry}
            material={materials.Ch07_body}
            skeleton={nodes.Ch07_Pants.skeleton}
          />
          <skinnedMesh
            name='Ch07_Shirt'
            geometry={nodes.Ch07_Shirt.geometry}
            material={materials.Ch07_body}
            skeleton={nodes.Ch07_Shirt.skeleton}
          />
          <skinnedMesh
            name='Ch07_Suit'
            geometry={nodes.Ch07_Suit.geometry}
            material={materials.Ch07_body}
            skeleton={nodes.Ch07_Suit.skeleton}
          />
        </group>
        <group
          name='Armature'
          position={[-4.59, -4.42, 4.14]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.05, 0.06, 0.05]}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name='Ch16_Body1'
            geometry={nodes.Ch16_Body1.geometry}
            material={materials['Ch16_Body.002']}
            skeleton={nodes.Ch16_Body1.skeleton}
          />
          <skinnedMesh
            name='Ch16_Cap'
            geometry={nodes.Ch16_Cap.geometry}
            material={materials['Ch16_body1.002']}
            skeleton={nodes.Ch16_Cap.skeleton}
          />
          <skinnedMesh
            name='Ch16_Eyelashes'
            geometry={nodes.Ch16_Eyelashes.geometry}
            material={materials['Ch16_eyelashes.002']}
            skeleton={nodes.Ch16_Eyelashes.skeleton}
          />
          <skinnedMesh
            name='Ch16_Mask'
            geometry={nodes.Ch16_Mask.geometry}
            material={materials['Ch16_body1.002']}
            skeleton={nodes.Ch16_Mask.skeleton}
          />
          <skinnedMesh
            name='Ch16_Pants'
            geometry={nodes.Ch16_Pants.geometry}
            material={materials['Ch16_Body.002']}
            skeleton={nodes.Ch16_Pants.skeleton}
          />
          <skinnedMesh
            name='Ch16_Shirt'
            geometry={nodes.Ch16_Shirt.geometry}
            material={materials['Ch16_Body.002']}
            skeleton={nodes.Ch16_Shirt.skeleton}
          />
          <skinnedMesh
            name='Ch16_Shoes'
            geometry={nodes.Ch16_Shoes.geometry}
            material={materials['Ch16_body1.002']}
            skeleton={nodes.Ch16_Shoes.skeleton}
          />
        </group>
        <mesh
          name='Plane'
          geometry={nodes.Plane.geometry}
          material={materials.MaterialFloor}
          position={[1.57, -5.52, -9.63]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25}
        >
          <meshBasicMaterial map={floorTexture} map-flipY={false} />
        </mesh>
        <group
          name='Book2'
          position={[-7.9, -0.49, 1.66]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={[0.21, 0.83, 0.23]}
        >
          <mesh
            name='Cylinder013'
            geometry={nodes.Cylinder013.geometry}
            material={materials.MaterialRed}
          />
          <mesh
            name='Cylinder013_1'
            geometry={nodes.Cylinder013_1.geometry}
            material={materials.MaterialWhite}
          />
        </group>
        <group
          name='Book1'
          position={[-8.01, -0.05, 1.49]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={[0.21, 0.83, 0.23]}
        >
          <mesh
            name='Book1_1'
            geometry={nodes.Book1_1.geometry}
            material={materials.MaterialBlue}
          />
          <mesh
            name='Book1_2'
            geometry={nodes.Book1_2.geometry}
            material={materials.MaterialWhite}
          />
        </group>
        <mesh
          name='Shelf1'
          geometry={nodes.Shelf1.geometry}
          material={materials.MaterialDoorWood}
          position={[24.42, -5.59, -21.19]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[5, 3.5, 4]}
        >
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <mesh
          name='Shelf2'
          geometry={nodes.Shelf2.geometry}
          material={materials.MaterialDoorWood}
          position={[24.47, -5.76, -13.21]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[3, 5, 4]}
        >
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <group
          name='PicFrame'
          position={[2.25, 7.87, -34.36]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.23, 3.04, 2.92]}
        >
          <mesh
            name='Cube028'
            geometry={nodes.Cube028.geometry}
            material={materials['Material.036']}
          />
          <mesh
            name='Cube028_1'
            geometry={nodes.Cube028_1.geometry}
            material={materials['Material.037']}
          />
        </group>
        <group
          name='Door'
          position={[18.39, 2.92, -33.9]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.15, 8, 5]}
        >
          <mesh
            name='Door_1'
            geometry={nodes.Door_1.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Door_2'
            geometry={nodes.Door_2.geometry}
            material={materials.MaterialMetalDoorHand}
          />
        </group>
        <mesh
          name='Shelf3'
          geometry={nodes.Shelf3.geometry}
          material={materials.MaterialDoorWood}
          position={[-11.74, -5.76, -32.48]}
          scale={[3, 5, 4]}
        >
          <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
        </mesh>
        <group
          name='Pen'
          position={[-6.45, -0.59, 1.28]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={[0.07, 0.69, 0.07]}
        >
          <mesh
            name='Cylinder015'
            geometry={nodes.Cylinder015.geometry}
            material={materials['Material.041']}
          />
          <mesh
            name='Cylinder015_1'
            geometry={nodes.Cylinder015_1.geometry}
            material={materials['Material.042']}
          />
          <mesh
            name='Cylinder015_2'
            geometry={nodes.Cylinder015_2.geometry}
            material={materials['Material.043']}
          />
          <mesh
            name='Cylinder015_3'
            geometry={nodes.Cylinder015_3.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <mesh
          name='Bench'
          geometry={nodes.Bench.geometry}
          material={materials.MaterialBenchWood}
          position={[-20.82, -2.31, -15.02]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[10.9, 0.19, 1.92]}
        >
          <meshBasicMaterial map={treeBenchTexture} map-flipY={false} />
        </mesh>
        <group
          name='Locker'
          position={[6.28, -3.08, -30.36]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.08, 1.95, 2.72]}
        >
          <mesh
            name='Cube034'
            geometry={nodes.Cube034.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube034_1'
            geometry={nodes.Cube034_1.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <group
          name='Locker001'
          position={[0.28, -3.08, -30.36]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.08, 1.95, 2.85]}
        >
          <mesh
            name='Cube035'
            geometry={nodes.Cube035.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube035_1'
            geometry={nodes.Cube035_1.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <group
          name='Locker002'
          position={[-11.7, -3.08, -30.36]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={[0.08, 1.95, 2.83]}
        >
          <mesh
            name='Cube036'
            geometry={nodes.Cube036.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube036_1'
            geometry={nodes.Cube036_1.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <group
          name='Locker003'
          position={[22.36, -2.92, -13.29]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.08, 1.95, 2.72]}
        >
          <mesh
            name='Cube037'
            geometry={nodes.Cube037.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube037_1'
            geometry={nodes.Cube037_1.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <group
          name='Locker004'
          position={[22.36, -2.92, -7.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.08, 1.95, 2.72]}
        >
          <mesh
            name='Cube038'
            geometry={nodes.Cube038.geometry}
            material={materials.MaterialDoorWood}
          >
            <meshBasicMaterial map={lockerWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube038_1'
            geometry={nodes.Cube038_1.geometry}
            material={materials.MaterialLockerHand}
          />
        </group>
        <group
          name='Bin'
          position={[23.94, -4.03, -30.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={1.4}
        >
          <mesh
            name='Cylinder016'
            geometry={nodes.Cylinder016.geometry}
            material={materials.MaterialGreen}
          />
          <mesh
            name='Cylinder016_1'
            geometry={nodes.Cylinder016_1.geometry}
            material={materials.MaterialMetalBin}
          />
        </group>
        <mesh
          name='Table'
          geometry={nodes.Table.geometry}
          material={materials.MaterialTable}
          position={[-8.33, -3.17, 2.5]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.18, 2.19, 0.12]}
        >
          <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
        </mesh>
        <group
          name='Chair1'
          position={[0.36, 1.32, -8.87]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[2.1, 0.41, 0.13]}
        >
          <mesh
            name='Cube014'
            geometry={nodes.Cube014.geometry}
            material={materials.MaterialChairWood}
          >
            <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube014_1'
            geometry={nodes.Cube014_1.geometry}
            material={materials.MaterialCuireBlack}
          >
            <meshBasicMaterial map={leatherTexture} map-flipY={false} />
          </mesh>
        </group>
        <group
          name='Chair2'
          position={[-6.24, 1.32, -9.12]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[2.1, 0.41, 0.15]}
        >
          <mesh
            name='Cube021'
            geometry={nodes.Cube021.geometry}
            material={materials.MaterialChairWood}
          >
            <meshBasicMaterial map={tableWoodTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cube021_1'
            geometry={nodes.Cube021_1.geometry}
            material={materials.MaterialCuireBlack}
          >
            <meshBasicMaterial map={leatherTexture} map-flipY={false} />
          </mesh>
        </group>
        <group
          name='Leg'
          position={[-4.36, -4.17, 4.48]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.23, 1.04, 0.23]}
        >
          <mesh
            name='Cylinder010'
            geometry={nodes.Cylinder010.geometry}
            material={materials.MaterialSteelGray}
          >
            <meshBasicMaterial map={metalTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cylinder010_1'
            geometry={nodes.Cylinder010_1.geometry}
            material={materials.MaterialMedChairLegBlack}
          >
            <meshBasicMaterial map={leatherTexture} map-flipY={false} />
          </mesh>
          <mesh
            name='Cylinder010_2'
            geometry={nodes.Cylinder010_2.geometry}
            material={materials.MaterialMedChairLeg}
          >
            <meshBasicMaterial map={metalTexture} map-flipY={false} />
          </mesh>
        </group>
        <group
          name='ChairDoc'
          position={[-4.58, -2.85, 4]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[2.36, 0.29, 1.65]}
        >
          <mesh
            name='Cube025'
            geometry={nodes.Cube025.geometry}
            material={materials.MaterialCuireBlack}
          />
          <mesh
            name='Cube025_1'
            geometry={nodes.Cube025_1.geometry}
            material={materials.MaterialMetalBin}
          />
        </group>
        <mesh
          name='Wall1'
          geometry={nodes.Wall1.geometry}
          material={materials.MaterialWall}
          position={[26.65, 4.58, -9.6]}
          scale={[0.1, 10, 25]}
        >
          <meshBasicMaterial map={wallTexture} map-flipY={false} />
        </mesh>
        <mesh
          name='Wall2'
          geometry={nodes.Wall2.geometry}
          material={materials.MaterialWall}
          position={[-23.51, 4.58, -9.6]}
          scale={[0.1, 10, 25]}
        >
          <meshBasicMaterial map={wallTexture} map-flipY={false} />
        </mesh>
        <mesh
          name='Wall4'
          geometry={nodes.Wall4.geometry}
          material={materials.MaterialWall}
          position={[1.68, 4.58, 15.52]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 10, 25.1]}
        >
          <meshBasicMaterial map={wallTexture} map-flipY={false} />
        </mesh>
        <mesh
          name='Wall4001'
          geometry={nodes.Wall4001.geometry}
          material={materials.MaterialWall}
          position={[1.68, 4.58, -34.73]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 10, 25.1]}
        >
          <meshBasicMaterial map={wallTexture} map-flipY={false} />
        </mesh>
        <group
          name='Screen'
          position={[2.3, 1.22, 1.08]}
          rotation={[1.4, -0.07, 0.35]}
          scale={0.23}
        >
          <mesh
            name='Plane005'
            geometry={nodes.Plane005.geometry}
            material={materials.MaterialCompLeg}
          />
          <mesh
            name='Plane005_1'
            geometry={nodes.Plane005_1.geometry}
            material={materials.MaterialCompScreen}
          />
        </group>
        <mesh
          name='CompLeg'
          geometry={nodes.CompLeg.geometry}
          material={materials.MaterialCompLeg}
          position={[2.27, -0.59, 1.13]}
          rotation={[0, -0.36, 0]}
          scale={[0.21, 0.21, 0.13]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/virtual_room_users_2.glb')
